version: '3'

services:
  db:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: smart-education
      POSTGRES_USER: smart-education
      POSTGRES_PASSWORD: smart-education
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: